-- CreateTable
CREATE TABLE "Config" (
    "id" INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT DEFAULT 1,
    "apertura" INTEGER NOT NULL DEFAULT 9,
    "cierre" INTEGER NOT NULL DEFAULT 18,
    "pasoMin" INTEGER NOT NULL DEFAULT 15,
    "diasCerrados" TEXT NOT NULL DEFAULT '0'
);
